name: 'Quality Clouds Build Check for Salesforce'
description: 'Quality Clouds Build Check for Salesforce'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  token:
    description: 'You need to provide a valid API key to connect the Quality Clouds ruleset against which your code will be checked'
    required: true
  mode:
    description: 'Use cloud mode to runh a Feature branch scan'
    required: false
  url_id:
    description: 'The instance Id. Required when cloud mode is enabled.'
    required: false
  api_url:
    description: 'Use cloud mode to runh a Feature branch scan'
    required: false
  version:
    description: 'Customize runner version'
    required: false
  review:
    description: 'Only used if mode == cloud. Boolean. default False. If True, scan will create a pull request review with inline comments with the issues '
    required: false
  allIssues:
    description: 'Only used if mode == cloud. Boolean. default False. If True, scan results will show blockers and no blocker issues'
    required: false    
  gitHubToken:
    description: 'Only used if review == True. secrets.GITHUB_TOKEN' 
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'